name: Integration continue

on:
    push:
        branches: ["main"]

jobs:
    hello:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: 18.x
            - name: Run test
              run: echo Hello le test
